# Generated by Django 4.2.4 on 2024-03-08 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('almacen_app', '0002_loggerusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='campo_predefinido',
            field=models.CharField(blank=True, choices=[('neumaticos', 'Neumáticos'), ('frenos', 'Frenos'), ('filtros', 'Filtros'), ('motor', 'Motor'), ('aceites_lubricantes', 'Aceites y Lubricantes'), ('limppiaparabrisas_escobillas', 'Limpiaparabrisas y Escobillas'), ('suspension', 'Suspensión'), ('sistema_electrico', 'Sistema Eléctrico'), ('encendido_precalentamiento', 'Endendido y Precalentamiento'), ('correas_cadenas_rodillos', 'Correas-Cadenas-Rodillos'), ('carroceria', 'Carrocería'), ('calefaccion_ventilacion', 'Calefacción y Ventilación'), ('baterias', 'Baterías'), ('sistema_combustible', 'Sistema de Combustible'), ('direccion', 'Dirección'), ('amortiguacion', 'Amortiguación'), ('sistema_refrigeracion', 'Sistema de Refrigeración'), ('juntas_retrenes', 'Juntas y Retrenes'), ('interior', 'Interior'), ('embrague', 'Embrague'), ('caja_cambios', 'Caja de Cambios'), ('aire_acondicionado', 'Aire Acondicionado'), ('rodamientos', 'Rodamientos'), ('transmision_diferencial', 'Transmisión y Diferencial'), ('kit_reparacion', 'Kit de Reparación'), ('accesorios', 'Accesorios'), ('tuberias_mangueras', 'Tuberías y Mangueras'), ('iluminacion', 'Iluminación')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='compatibilidad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.TextField()),
                ('estado', models.CharField(choices=[('realizado', 'Realizado'), ('espera', 'Espera'), ('aceptado', 'Aceptado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
