# Generated by Django 4.2.4 on 2024-03-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0003_alter_producto_campo_predefinido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=50),
        ),
    ]
