# Generated by Django 4.2.4 on 2024-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0005_alter_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='campo_predefinido',
            field=models.CharField(blank=True, choices=[('neumaticos', 'Neumáticos'), ('frenos', 'Frenos'), ('filtros', 'Filtros'), ('motor', 'Motor'), ('aceites_lubricantes', 'Aceites y Lubricantes'), ('limpiaparabrisas_escobillas', 'Limpiaparabrisas y Escobillas'), ('suspension', 'Suspensión'), ('sistema_electrico', 'Sistema Eléctrico'), ('encendido_precalentamiento', 'Endendido y Precalentamiento'), ('correas_cadenas_rodillos', 'Correas-Cadenas-Rodillos'), ('carroceria', 'Carrocería'), ('calefaccion_ventilacion', 'Calefacción y Ventilación'), ('baterias', 'Baterías'), ('sistema_combustible', 'Sistema de Combustible'), ('direccion', 'Dirección'), ('amortiguacion', 'Amortiguación'), ('sistema_refrigeracion', 'Sistema de Refrigeración'), ('juntas_retrenes', 'Juntas y Retrenes'), ('interior', 'Interior'), ('embrague', 'Embrague'), ('caja_cambios', 'Caja de Cambios'), ('aire_acondicionado', 'Aire Acondicionado'), ('rodamientos', 'Rodamientos'), ('transmision_diferencial', 'Transmisión y Diferencial'), ('kit_reparacion', 'Kit de Reparación'), ('accesorios', 'Accesorios'), ('tuberias_mangueras', 'Tuberías y Mangueras'), ('iluminacion', 'Iluminación')], max_length=50, null=True),
        ),
    ]
