# Generated by Django 4.2.4 on 2024-03-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0007_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='compatibilidad',
            field=models.CharField(blank=True, null=True),
        ),
    ]
