# Generated by Django 4.2.4 on 2024-04-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0008_alter_producto_compatibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
